In [1]:
# basic library
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)

In [2]:
# list algoritma
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold, cross_val_score,GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [3]:
# alat evaluasi
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import classification_report

# 1. Data Preprocesing

In [4]:
url = 'https://raw.githubusercontent.com/arofiqimaulana/dataset/master/iris.csv'
df = pd.read_csv(url)

# split data
kolom_X = ['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']
kolom_y = ['target']

X = df[kolom_X]
y = df[kolom_y]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# 2. Modeling

In [5]:
# fit model
model = DecisionTreeClassifier().fit(X_train, y_train)

In [6]:
# prediksi
y_pred = model.predict(X_test)

In [7]:
# evaluasi model menggunakan confusion matriks
confusion_matrix = confusion_matrix(y_test, y_pred,labels=list(set(y['target'])))
print(confusion_matrix)

[[12  0  0]
 [ 0  7  0]
 [ 0  1 10]]


In [8]:
# evaluasi model menggunakan presisi, recall, f1-score, dan support
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      1.00      0.93         7
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



# 3. Membandingkan antar algoritma

In [9]:
cv=StratifiedKFold(n_splits=10)

models = []
models.append(('CART', DecisionTreeClassifier()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('Naive Bayes', GaussianNB()))
models.append(('SVM', SVC()))
models.append(('Random Forest', RandomForestClassifier()))
models.append(('Logistic Regression', LogisticRegression()))


results = []
names = []
tabel=[]
for name, model in models:
    akurasi=cross_val_score(model, X_train, np.ravel(y_train),cv=cv)
    results.append(akurasi)
    names.append(name)
    hasil = "%s: %f" % (name, akurasi.mean())
    tabel.append(hasil)
tabel

C:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

['CART: 0.933333',
 'KNN: 0.966667',
 'Naive Bayes: 0.950000',
 'SVM: 0.966667',
 'Random Forest: 0.925000',
 'Logistic Regression: 0.950000']